# Generated by Django 2.1.7 on 2019-02-19 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='passing_year',
            field=models.PositiveIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2019)]),
        ),
    ]
