# Generated by Django 2.1.7 on 2019-02-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190219_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='passing_year',
            field=models.PositiveIntegerField(default=2019),
        ),
    ]
