# Generated by Django 2.1.7 on 2019-02-19 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=20)),
                ('DateAdded', models.DateTimeField(auto_now=True)),
                ('Requirements', models.CharField(max_length=50)),
                ('Experiecne', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('Salary', models.IntegerField(default=150000, validators=[django.core.validators.MinValueValidator(150000), django.core.validators.MaxValueValidator(1300000)])),
                ('Description', models.TextField()),
                ('HrMail', models.EmailField(max_length=30)),
            ],
        ),
    ]
